### ISSUE TITLE
Can't copy certain code from sites

### ISSUE THREAD

**Issue by darukutsu** [LaurenceWarne/qute-code-hint#3]
I wasn't able to copy certain codeblocks from sites like:
https://www.npmjs.com/package/qutejs
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-list/

Apparently it was ElementTree parser [problem](https://stackoverflow.com/a/35591507/15245191)

After adding this to script, I can now copy
```
def parse_text_content(element):
    magic = '''<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" [
                <!ENTITY nbsp ' '>
                ]>'''  # You can define more entities here, if needed
    root = ET.fromstring(magic + element)
    text = ET.tostring(root, encoding="unicode", method="text")
    text = html.unescape(text)
    return text
```

**Comment by LaurenceWarne** [comment]
Done in https://github.com/LaurenceWarne/qute-code-hint/commit/a9d8f5a51353c463aabb4d888873a5e49d17b0a5, thanks! (I added you as a co-author - I hope you don't mind :slightly_smiling_face:)

**Comment by darukutsu** [comment]
Yeah, sure np. Feel free to close.
